const fs = require("fs")
const path = require("path")

fs.mkdirSync(path.join("src", "app", "admin"), { recursive: true })
fs.mkdirSync(path.join("src", "app", "api", "publish"), { recursive: true })

// === FILE 1: Admin Page ===
fs.writeFileSync("src/app/admin/page.tsx", [
'"use client"',
'import { useState, useEffect } from "react"',
'',
'const SECTIONS = [',
'  "site", "hero", "about", "book", "expertise",',
'  "impact", "offerings", "experience", "journal",',
'  "contact", "partners", "nav", "footer"',
']',
'const PASSWORD = "admin123"',
'',
'export default function AdminPage() {',
'  const [loggedIn, setLoggedIn] = useState(false)',
'  const [password, setPassword] = useState("")',
'  const [section, setSection] = useState("hero")',
'  const [data, setData] = useState("{}")',
'  const [loading, setLoading] = useState(false)',
'  const [saving, setSaving] = useState(false)',
'  const [message, setMessage] = useState("")',
'',
'  useEffect(() => { if (loggedIn) loadSection(section) }, [loggedIn, section])',
'',
'  async function loadSection(sec) {',
'    setLoading(true)',
'    setMessage("")',
'    try {',
'      const baseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL',
'      const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY',
'      const url = baseUrl + "/rest/v1/site_content?section=eq." + sec',
'      const res = await fetch(url, {',
'        headers: { apikey: key, Authorization: "Bearer " + key }',
'      })',
'      const rows = await res.json()',
'      if (rows && rows.length > 0) {',
'        setData(JSON.stringify(rows[0].data, null, 2))',
'      } else {',
'        const { siteData } = await import("@/lib/site-data")',
'        const val = (siteData as any)[sec]',
'        setData(val ? JSON.stringify(val, null, 2) : "{}")',
'      }',
'    } catch (e) {',
'      setMessage("Error: " + (e instanceof Error ? e.message : String(e)))',
'    }',
'    setLoading(false)',
'  }',
'',
'  async function save() {',
'    setSaving(true)',
'    setMessage("")',
'    try {',
'      const parsed = JSON.parse(data)',
'      const baseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL',
'      const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY',
'      const res = await fetch(baseUrl + "/rest/v1/site_content", {',
'        method: "POST",',
'        headers: {',
'          apikey: key,',
'          Authorization: "Bearer " + key,',
'          "Content-Type": "application/json",',
'          Prefer: "resolution=merge-duplicates"',
'        },',
'        body: JSON.stringify({ section: section, data: parsed })',
'      })',
'      if (res.ok) setMessage("Saved!")',
'      else setMessage("Error: " + await res.text())',
'    } catch (e) {',
'      setMessage("Invalid JSON")',
'    }',
'    setSaving(false)',
'  }',
'',
'  async function publish() {',
'    setMessage("Triggering deploy...")',
'    try {',
'      const res = await fetch("/api/publish", { method: "POST" })',
'      const json = await res.json()',
'      if (res.ok) setMessage("Deploy triggered! Site updates in 1-2 min.")',
'      else setMessage("Error: " + (json.error || "Failed"))',
'    } catch (e) {',
'      setMessage("Error: " + (e instanceof Error ? e.message : String(e)))',
'    }',
'  }',
'',
'  if (!loggedIn) return (',
'    <div style={{maxWidth:400,margin:"100px auto",padding:40,fontFamily:"system-ui"}}>',
'      <h2>Admin Panel</h2>',
'      <input type="password" value={password}',
'        onChange={e => setPassword(e.target.value)} placeholder="Password"',
'        onKeyDown={e => { if (e.key === "Enter" && password === PASSWORD) setLoggedIn(true) }}',
'        style={{width:"100%",padding:10,margin:"16px 0",fontSize:16,boxSizing:"border-box"}} />',
'      <button onClick={() => {',
'        if (password === PASSWORD) setLoggedIn(true)',
'        else setMessage("Wrong password")',
'      }} style={{padding:"10px 32px",fontSize:16,cursor:"pointer"}}>Login</button>',
'      {message && <p style={{color:"red",marginTop:12}}>{message}</p>}',
'    </div>',
'  )',
'',
'  return (',
'    <div style={{display:"flex",height:"100vh",fontFamily:"system-ui",margin:0}}>',
'      <div style={{width:220,background:"#0f172a",color:"#e2e8f0",padding:20,overflowY:"auto"}}>',
'        <h3 style={{margin:"0 0 20px",fontSize:13,textTransform:"uppercase",letterSpacing:1,color:"#94a3b8"}}>Sections</h3>',
'        {SECTIONS.map(s => (',
'          <div key={s} onClick={() => setSection(s)}',
'            style={{padding:"8px 12px",cursor:"pointer",borderRadius:6,marginBottom:2,',
'              background:section===s?"#3b82f6":"transparent",fontSize:14}}>{s}</div>',
'        ))}',
'        <div style={{marginTop:24,borderTop:"1px solid #1e293b",paddingTop:16}}>',
'          <button onClick={publish}',
'            style={{width:"100%",padding:12,background:"#22c55e",color:"#fff",border:"none",',
'              borderRadius:8,cursor:"pointer",fontWeight:600,fontSize:14}}>Publish Changes</button>',
'          <p style={{fontSize:11,color:"#64748b",marginTop:8}}>Rebuilds site with latest data</p>',
'        </div>',
'      </div>',
'      <div style={{flex:1,display:"flex",flexDirection:"column"}}>',
'        <div style={{padding:"12px 24px",borderBottom:"1px solid #e2e8f0",display:"flex",alignItems:"center",gap:12,background:"#f8fafc"}}>',
'          <h2 style={{margin:0,fontSize:16}}>{section}</h2>',
'          <button onClick={save} disabled={saving}',
'            style={{padding:"6px 20px",background:"#3b82f6",color:"#fff",border:"none",',
'              borderRadius:6,cursor:"pointer",fontSize:14}}>{saving?"Saving...":"Save"}</button>',
'          {message && <span style={{fontSize:13,',
'            color:message.includes("Error")||message.includes("Invalid")?"red":"#16a34a"}}>{message}</span>}',
'        </div>',
'        <textarea value={loading?"Loading...":data} onChange={e => setData(e.target.value)}',
'          style={{flex:1,padding:20,border:"none",fontSize:13,fontFamily:"monospace",',
'            resize:"none",outline:"none",lineHeight:1.6}} />',
'      </div>',
'    </div>',
'  )',
'}',
].join("\n"))

// === FILE 2: Publish API Route ===
fs.writeFileSync("src/app/api/publish/route.ts", [
'import { NextResponse } from "next/server"',
'',
'export async function POST() {',
'  const hookUrl = process.env.VERCEL_DEPLOY_HOOK',
'  if (!hookUrl) {',
'    return NextResponse.json({ error: "Deploy hook not configured" }, { status: 500 })',
'  }',
'  try {',
'    await fetch(hookUrl, { method: "POST" })',
'    return NextResponse.json({ ok: true })',
'  } catch (e) {',
'    return NextResponse.json({ error: String(e) }, { status: 500 })',
'  }',
'}',
].join("\n"))

// === FILE 3: Prebuild Script ===
fs.writeFileSync("scripts/prebuild.mjs", [
'import { readFileSync, writeFileSync } from "fs"',
'',
'const SB_URL = process.env.NEXT_PUBLIC_SUPABASE_URL',
'const SB_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY',
'',
'if (!SB_URL || !SB_KEY) {',
'  console.log("No Supabase credentials - using existing site-data.ts")',
'  process.exit(0)',
'}',
'',
'try {',
'  const res = await fetch(SB_URL + "/rest/v1/site_content?select=*", {',
'    headers: { apikey: SB_KEY, Authorization: "Bearer " + SB_KEY }',
'  })',
'  const rows = await res.json()',
'  if (!Array.isArray(rows) || rows.length === 0) {',
'    console.log("Supabase empty - using existing site-data.ts")',
'    process.exit(0)',
'  }',
'  const obj = {}',
'  for (const row of rows) obj[row.section] = row.data',
'  let comments = ""',
'  try {',
'    const existing = readFileSync("src/lib/site-data.ts", "utf8")',
'    const lines = existing.split("\\n")',
'    let cl = []',
'    for (const line of lines) {',
'      if (line.trimStart().startsWith("//")) cl.push(line)',
'      else break',
'    }',
'    if (cl.length > 0) comments = cl.join("\\n") + "\\n"',
'  } catch (e) {}',
'  const output = comments + "export const siteData = " + JSON.stringify(obj, null, 2) + " as const\\n"',
'  writeFileSync("src/lib/site-data.ts", output)',
'  console.log("site-data.ts updated from Supabase (" + rows.length + " sections)")',
'} catch (e) {',
'  console.log("Supabase error - using existing site-data.ts: " + String(e))',
'  process.exit(0)',
'}',
].join("\n"))

// === UPDATE package.json ===
const pkg = JSON.parse(fs.readFileSync("package.json", "utf8"))
pkg.scripts.build = "node scripts/prebuild.mjs && next build"
fs.writeFileSync("package.json", JSON.stringify(pkg, null, 2) + "\n")

console.log("")
console.log("=== DONE - 3 files created, package.json updated ===")
console.log("Next: git add . && git commit -m \"Add admin panel\" && git push")